### PR TITLE
Add Travis CI integration

### LINKED ISSUE #8: Build here `conanio/conantests` docker image
After https://github.com/conan-io/conan_ci_jenkins/pull/3, we can build in this repo the docker images we are using in our tests. Here in this repo we know the tools we need, the paths to those tools, we can even run tests using a stable Conan ....

First step is to move it from https://github.com/conan-io/conan-docker-tools/tree/master/conan_tests

### PR DESCRIPTION
**Pull request by jgsogo**
Objectives of this PR:
 * Add CI for the code in this repository: add dummy tests (python + groovy)
 * Generate docker images using the CI and upload them to DockerHub from master job
   + right now we need to generate `conanio/conan_tests`. **It has to be exactly the same image we have in the [conan-docker-tools](https://github.com/conan-io/conan-docker-tools/tree/master/conan_tests)**. **PLEASE, double check it** ⚠️ 
   + in the future we might use some other images for our testing, they will be generated here too

closes #8

### CODE REVIEW

**Comment by uilianries** [comment]
I'm curious if you have any idea for testing the docker image?

**Comment by uilianries** [comment]
I'm checking some changes which can solve hadolint errors, give some minutes

**Comment by uilianries** [comment]
@jgsogo Try this docker recipe: https://gist.github.com/uilianries/7fe7395412bfb0af0cc78732fe5532e0#file-dockerfile, or just update yours.

It won't generate errors from Hado Lint.

**Comment by jgsogo** [comment]
> I'm curious if you have any idea for testing the docker image?

Right now, our tests (the CI) are the actual testing of the docker image. It is quite difficult to have a "wrong" image so that all our test suite works. Yes, I know this is a very naïve approach... in the future I want to add tests to these images, yes, to check that the installed things are actually working and some environment variables are defined. I need to thing about this, but if you want, I can share with you my ideas when I have a draft.

**Comment by jgsogo** [comment]
@danimtb @uilianries Finally no linter for this image (new ones will have it), but I have fixed the versions of the python packages

**Comment by jgsogo** [comment]
This will fail in `master` as we don't have the DOCKER_USERNAME and DOCKER_PASSWORD set yet... but it will work for the PRs

**Pull request merged**
